# tarja/entities.py
# [ENTITIES] GENERATED by tools/gen_entities.py from spec/entities/*.yaml. Do not edit by hand:
#   change the yaml, then run `python tools/gen_entities.py`. CI fails if this file is stale.
#   The core has zero deps, so the registry is plain Python at runtime.

from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass

from tarja.validators import (
    cartao,
    cep,
    cib,
    cnh,
    cnj,
    cnm,
    cnpj,
    cns,
    cpf,
    iptu,
    matricula,
    nis,
    pix,
    placa,
    renavam,
    telefone,
    titulo,
)

# [ENTITIES-TIERS] tier order, lower = stronger evidence. Used to break overlaps.
TIER_RANK = {"N1": 1, "N2": 2, "N3": 3, "N4": 4}


@dataclass(frozen=True)
class Pattern:
    """EN: One candidate regex. PT: Uma regex de candidato."""

    name: str
    regex: re.Pattern[str]
    score: float


@dataclass(frozen=True)
class EntitySpec:
    """EN: Everything the engine needs to know about one entity. Mirrors the yaml fields.
    PT: Tudo q o motor precisa saber de 1 entidade. Espelha os campos do yaml.
    """

    id: str
    tier: str
    patterns: tuple[Pattern, ...]
    validator: Callable[[str], bool] | None
    context_words: tuple[str, ...]
    context_window: int
    context_required: bool
    score_with_context: float
    score_without_context: float
    # [ENTITIES-ADJACENT] optional tight context: a word right before (or right after) the value, at most
    #   context_gap characters away. When set, it replaces the window search for this entity.
    context_before: tuple[str, ...] = ()
    context_after: tuple[str, ...] = ()
    context_gap: int = 0


def _p(name: str, regex: str, score: float) -> Pattern:
    # [ENTITIES-PATTERN] helper, compiles once at import
    return Pattern(name, re.compile(regex), score)


# [ENTITIES-REGISTRY] order comes from spec/registry.yaml and matters only as the last overlap tie-breaker
ENTITIES: dict[str, EntitySpec] = {
    # [ENTITIES-CPF]
    "BR_CPF": EntitySpec(
        id="BR_CPF",
        tier="N1",
        patterns=(
            _p("cpf_formatted", r"\b\d{3}\.\d{3}\.\d{3}-\d{2}\b", 0.5),
            _p("cpf_compact", r"\b\d{11}\b", 0.1),
            _p("cpf_irregular_punctuation", r"\b\d{3}[\s.]?\d{3}[\s.]?\d{3}[\s\-./]?\d{2}\b", 0.3),
        ),
        validator=cpf.is_valid,
        context_words=(
            "cpf",
            "cadastro de pessoa fisica",
            "cadastro de pessoas fisicas",
            "inscrito no cpf",
            "portador do cpf",
            "contribuinte",
        ),
        context_window=50,
        context_required=False,
        score_with_context=0.95,
        score_without_context=0.85,
    ),
    # [ENTITIES-CNPJ]
    "BR_CNPJ": EntitySpec(
        id="BR_CNPJ",
        tier="N1",
        patterns=(
            _p("cnpj_formatted", r"\b[0-9A-Za-z]{2}\.[0-9A-Za-z]{3}\.[0-9A-Za-z]{3}/[0-9A-Za-z]{4}-\d{2}\b", 0.5),
            _p("cnpj_compact", r"\b[0-9A-Za-z]{12}\d{2}\b", 0.1),
            _p("cnpj_spaced", r"\b[0-9A-Za-z]{2}[\s.][0-9A-Za-z]{3}[\s.][0-9A-Za-z]{3}[\s/][0-9A-Za-z]{4}[\s-]\d{2}\b", 0.3),
        ),
        validator=cnpj.is_valid,
        context_words=(
            "cnpj",
            "cadastro nacional da pessoa juridica",
            "inscrita no cnpj",
            "inscrita sob o",
            "pessoa juridica",
            "empresa",
        ),
        context_window=50,
        context_required=False,
        score_with_context=0.95,
        score_without_context=0.85,
    ),
    # [ENTITIES-CNS]
    "BR_CNS": EntitySpec(
        id="BR_CNS",
        tier="N1",
        patterns=(
            _p("cns_formatted", r"\b[12789]\d{2}[\s.]\d{4}[\s.]\d{4}[\s.]\d{4}\b", 0.5),
            _p("cns_compact", r"\b[12789]\d{14}\b", 0.2),
        ),
        validator=cns.is_valid,
        context_words=(
            "cns",
            "cartao sus",
            "cartao do sus",
            "cartao nacional de saude",
            "sus",
        ),
        context_window=50,
        context_required=False,
        score_with_context=0.95,
        score_without_context=0.85,
    ),
    # [ENTITIES-NIS]
    "BR_NIS": EntitySpec(
        id="BR_NIS",
        tier="N1",
        patterns=(
            _p("nis_formatted", r"\b\d{3}\.\d{5}\.\d{2}-\d\b", 0.5),
            _p("nis_compact", r"\b\d{11}\b", 0.1),
            _p("nis_spaced", r"\b\d{3}[\s.]\d{5}[\s.]\d{2}[\s-]\d\b", 0.3),
        ),
        validator=nis.is_valid,
        context_words=(
            "nis",
            "pis",
            "pasep",
            "nit",
            "pis/pasep",
            "numero de identificacao social",
        ),
        context_window=50,
        context_required=False,
        score_with_context=0.95,
        score_without_context=0.8,
    ),
    # [ENTITIES-CNJ]
    "BR_CNJ": EntitySpec(
        id="BR_CNJ",
        tier="N1",
        patterns=(
            _p("cnj_formatted", r"\b\d{7}-\d{2}\.\d{4}\.\d\.\d{2}\.\d{4}\b", 0.6),
            _p("cnj_compact", r"\b\d{20}\b", 0.1),
            _p("cnj_spaced", r"\b\d{7}[\s-]\d{2}[\s.]\d{4}[\s.]\d[\s.]\d{2}[\s.]\d{4}\b", 0.3),
        ),
        validator=cnj.is_valid,
        context_words=(
            "processo",
            "autos",
            "proc.",
            "numero do processo",
            "acao",
            "recurso",
        ),
        context_window=60,
        context_required=False,
        score_with_context=0.95,
        score_without_context=0.9,
    ),
    # [ENTITIES-TITULO-ELEITOR]
    "BR_TITULO_ELEITOR": EntitySpec(
        id="BR_TITULO_ELEITOR",
        tier="N1",
        patterns=(_p("titulo_spaced", r"\b\d{4}\s?\d{4}\s?\d{4}\b", 0.3),),
        validator=titulo.is_valid,
        context_words=(
            "titulo de eleitor",
            "titulo eleitoral",
            "inscricao eleitoral",
            "inscricao",
            "eleitor",
            "eleitora",
            "zona eleitoral",
            "justica eleitoral",
        ),
        context_window=60,
        context_required=False,
        score_with_context=0.95,
        score_without_context=0.8,
    ),
    # [ENTITIES-CNH]
    "BR_CNH": EntitySpec(
        id="BR_CNH",
        tier="N1",
        patterns=(_p("cnh_compact", r"\b\d{11}\b", 0.1),),
        validator=cnh.is_valid,
        context_words=(
            "cnh",
            "carteira de habilitacao",
            "carteira nacional de habilitacao",
            "habilitacao",
            "registro da cnh",
        ),
        context_window=50,
        context_required=True,
        score_with_context=0.95,
        score_without_context=0.85,
    ),
    # [ENTITIES-RENAVAM]
    "BR_RENAVAM": EntitySpec(
        id="BR_RENAVAM",
        tier="N1",
        patterns=(
            _p("renavam_11", r"\b\d{11}\b", 0.1),
            _p("renavam_9", r"\b\d{9}\b", 0.1),
        ),
        validator=renavam.is_valid,
        context_words=(
            "renavam",
            "registro nacional de veiculos automotores",
            "codigo renavam",
        ),
        context_window=50,
        context_required=True,
        score_with_context=0.95,
        score_without_context=0.85,
    ),
    # [ENTITIES-PLACA]
    "BR_PLACA": EntitySpec(
        id="BR_PLACA",
        tier="N2",
        patterns=(
            _p("placa_old", r"\b[A-Z]{3}-?\d{4}\b", 0.4),
            _p("placa_mercosur", r"\b[A-Z]{3}\d[A-Z]\d{2}\b", 0.5),
        ),
        validator=placa.is_valid,
        context_words=(
            "placa",
            "veiculo",
            "carro",
            "moto",
            "automovel",
        ),
        context_window=50,
        context_required=False,
        score_with_context=0.7,
        score_without_context=0.5,
    ),
    # [ENTITIES-PIX-EVP]
    "BR_PIX_EVP": EntitySpec(
        id="BR_PIX_EVP",
        tier="N2",
        patterns=(
            _p(
                "pix_uuid",
                r"\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}\b",
                0.3,
            ),
        ),
        validator=pix.is_valid,
        context_words=(
            "pix",
            "chave pix",
            "chave aleatoria",
            "chave",
        ),
        context_window=50,
        context_required=True,
        score_with_context=0.7,
        score_without_context=0.5,
    ),
    # [ENTITIES-TELEFONE]
    "BR_TELEFONE": EntitySpec(
        id="BR_TELEFONE",
        tier="N2",
        patterns=(_p("telefone", r"(?<![\d+])(?:\+?55[\s-]?)?\(?\d{2}\)?[\s-]?9?\d{4}[\s-]?\d{4}(?!\d)", 0.3),),
        validator=telefone.is_valid,
        context_words=(
            "tel",
            "telefone",
            "celular",
            "cel",
            "whatsapp",
            "whats",
            "contato",
            "fone",
            "ligar",
        ),
        context_window=40,
        context_required=False,
        score_with_context=0.7,
        score_without_context=0.5,
    ),
    # [ENTITIES-CEP]
    "BR_CEP": EntitySpec(
        id="BR_CEP",
        tier="N3",
        patterns=(_p("cep", r"\b\d{5}-?\d{3}\b", 0.2),),
        validator=cep.is_valid,
        context_words=(
            "cep",
            "codigo postal",
            "codigo de enderecamento postal",
        ),
        context_window=30,
        context_required=True,
        score_with_context=0.5,
        score_without_context=0.3,
    ),
    # [ENTITIES-CNM]
    "BR_CNM": EntitySpec(
        id="BR_CNM",
        tier="N1",
        patterns=(
            _p("cnm_formatted", r"\b\d{6}\.[23]\.\d{7}-?\d{2}\b", 0.6),
            _p("cnm_compact", r"\b\d{6}[23]\d{9}\b", 0.1),
            _p("cnm_spaced", r"\b\d{6}[\s.][23][\s.]\d{7}[\s-]\d{2}\b", 0.3),
        ),
        validator=cnm.is_valid,
        context_words=(
            "cnm",
            "codigo nacional de matricula",
            "matricula",
            "registro de imoveis",
            "imovel",
        ),
        context_window=60,
        context_required=False,
        score_with_context=0.95,
        score_without_context=0.9,
    ),
    # [ENTITIES-CIB]
    "BR_CIB": EntitySpec(
        id="BR_CIB",
        tier="N1",
        patterns=(
            _p("cib", r"\b[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{7}-?[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]\b", 0.2),
            _p("cib_spaced", r"\b[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]{7}\s[0-9A-HJKMNP-TV-Za-hjkmnp-tv-z]\b", 0.2),
        ),
        validator=cib.is_valid,
        context_words=(
            "cib",
            "cadastro imobiliario brasileiro",
            "cadastro imobiliario",
        ),
        context_window=50,
        context_required=True,
        score_with_context=0.95,
        score_without_context=0.9,
    ),
    # [ENTITIES-IPTU]
    "BR_IPTU": EntitySpec(
        id="BR_IPTU",
        tier="N3",
        patterns=(_p("iptu", r"\b\d[\d.\-/]{4,24}\d\b", 0.2),),
        validator=iptu.is_valid,
        context_words=(
            "iptu",
            "inscricao imobiliaria",
            "indice cadastral",
            "inscricao do imovel",
            "sql",
            "cadastro municipal",
        ),
        context_window=40,
        context_required=True,
        score_with_context=0.5,
        score_without_context=0.3,
    ),
    # [ENTITIES-MATRICULA-IMOVEL]
    "BR_MATRICULA_IMOVEL": EntitySpec(
        id="BR_MATRICULA_IMOVEL",
        tier="N3",
        patterns=(
            _p("matricula_dotted", r"\b\d{1,3}(?:\.\d{3}){1,2}\b", 0.2),
            _p("matricula_plain", r"\b\d{1,7}\b", 0.1),
        ),
        validator=matricula.is_valid,
        context_words=(
            "matricula do imovel",
            "matricula imobiliaria",
            "matricula n",
            "matricula no",
            "registro de imoveis",
            "cartorio de registro de imoveis",
        ),
        context_window=30,
        context_required=True,
        score_with_context=0.4,
        score_without_context=0.3,
        context_before=(
            "matricula",
            "matricula do imovel",
            "matricula imobiliaria",
            "matricula n",
            "matricula no",
            "matricula sob o n",
        ),
        context_after=(
            "registro de imoveis",
            "cartorio de registro de imoveis",
            "rgi",
            "cri",
        ),
        context_gap=4,
    ),
    # [ENTITIES-CARTAO]
    "BR_CARTAO": EntitySpec(
        id="BR_CARTAO",
        tier="N1",
        patterns=(
            _p("cartao_16", r"\b\d{4}[ -]?\d{4}[ -]?\d{4}[ -]?\d{4}\b", 0.5),
            _p("cartao_amex", r"\b\d{4}[ -]?\d{6}[ -]?\d{5}\b", 0.4),
            _p("cartao_compact", r"\b\d{13,19}\b", 0.1),
        ),
        validator=cartao.is_valid,
        context_words=(
            "cartao",
            "credito",
            "debito",
            "visa",
            "mastercard",
            "elo",
            "hipercard",
            "amex",
            "final",
        ),
        context_window=40,
        context_required=False,
        score_with_context=0.95,
        score_without_context=0.8,
    ),
}
