# tools/gen_entities.py
# [GEN-ENTITIES] Single source of truth: renders src/tarja/entities.py from spec/entities/*.yaml and
#   spec/registry.yaml (registry order). The core keeps zero runtime deps: yaml is read here, at dev time only.
#   CI runs `python tools/gen_entities.py --check`, which fails if the committed file is stale.
#
# usage:
#   python tools/gen_entities.py          # rewrite src/tarja/entities.py
#   python tools/gen_entities.py --check  # exit 1 if it would change

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "spec"
OUT = ROOT / "src" / "tarja" / "entities.py"

HEADER = '''# tarja/entities.py
# [ENTITIES] GENERATED by tools/gen_entities.py from spec/entities/*.yaml. Do not edit by hand:
#   change the yaml, then run `python tools/gen_entities.py`. CI fails if this file is stale.
#   The core has zero deps, so the registry is plain Python at runtime.

from __future__ import annotations

import re
from collections.abc import Callable
from dataclasses import dataclass

from tarja.validators import (
{imports}
)

# [ENTITIES-TIERS] tier order, lower = stronger evidence. Used to break overlaps.
TIER_RANK = {{"N1": 1, "N2": 2, "N3": 3, "N4": 4}}


@dataclass(frozen=True)
class Pattern:
    """EN: One candidate regex. PT: Uma regex de candidato."""

    name: str
    regex: re.Pattern[str]
    score: float


@dataclass(frozen=True)
class EntitySpec:
    """EN: Everything the engine needs to know about one entity. Mirrors the yaml fields.
    PT: Tudo q o motor precisa saber de 1 entidade. Espelha os campos do yaml.
    """

    id: str
    tier: str
    patterns: tuple[Pattern, ...]
    validator: Callable[[str], bool] | None
    context_words: tuple[str, ...]
    context_window: int
    context_required: bool
    score_with_context: float
    score_without_context: float
    # [ENTITIES-ADJACENT] optional tight context: a word right before (or right after) the value, at most
    #   context_gap characters away. When set, it replaces the window search for this entity.
    context_before: tuple[str, ...] = ()
    context_after: tuple[str, ...] = ()
    context_gap: int = 0


def _p(name: str, regex: str, score: float) -> Pattern:
    # [ENTITIES-PATTERN] helper, compiles once at import
    return Pattern(name, re.compile(regex), score)


# [ENTITIES-REGISTRY] order comes from spec/registry.yaml and matters only as the last overlap tie-breaker
ENTITIES: dict[str, EntitySpec] = {{
{entries}
}}
'''


def _lit(s: str) -> str:
    # raw string when safe, repr otherwise
    if '"' not in s and not s.endswith("\\") and "\n" not in s:
        return f'r"{s}"'
    return repr(s)


def _words(ws: list[str]) -> str:
    return "(" + "".join(f"{w!r}, " for w in ws).rstrip(" ") + ")" if ws else "()"


def load() -> list[dict]:
    order = yaml.safe_load((SPEC / "registry.yaml").read_text(encoding="utf-8"))["order"]
    specs = {}
    for f in sorted((SPEC / "entities").glob("*.yaml")):
        s = yaml.safe_load(f.read_text(encoding="utf-8"))
        specs[s["id"]] = s
    missing = set(specs) ^ set(order)
    if missing:
        sys.exit(f"spec/registry.yaml and spec/entities disagree on: {sorted(missing)}")
    return [specs[i] for i in order]


def render(specs: list[dict]) -> str:
    # [GEN-ENTITIES-RENDER]
    mods = sorted({s["validator"]["function"].split(".")[2] for s in specs if s.get("validator")})
    entries = []
    for s in specs:
        ctx, sc = s["context"], s["score"]
        pats = "\n".join(f"            _p({p['name']!r}, {_lit(p['regex'])}, {p['score']})," for p in s["patterns"])
        v = s.get("validator")
        validator = ".".join(v["function"].split(".")[2:]) if v else "None"
        lines = [
            f"    # [ENTITIES-{s['id'].removeprefix('BR_').replace('_', '-')}]",
            f"    {s['id']!r}: EntitySpec(",
            f"        id={s['id']!r},",
            f"        tier={s['tier']!r},",
            "        patterns=(",
            pats,
            "        ),",
            f"        validator={validator},",
            f"        context_words={_words(ctx['words'])},",
            f"        context_window={ctx.get('window', 50)},",
            f"        context_required={ctx.get('required', False)},",
            f"        score_with_context={sc['valid_with_context']},",
            f"        score_without_context={sc['valid_without_context']},",
        ]
        adj = ctx.get("adjacent")
        if adj:
            lines += [
                f"        context_before={_words(adj.get('before', []))},",
                f"        context_after={_words(adj.get('after', []))},",
                f"        context_gap={adj['gap']},",
            ]
        lines.append("    ),")
        entries.append("\n".join(lines))
    imports = "\n".join(f"    {m}," for m in mods)
    return HEADER.format(imports=imports, entries="\n".join(entries))


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Generate src/tarja/entities.py from spec/")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    new = render(load())
    try:
        # format the same way the repo does, so --check compares like with like
        import subprocess

        new = subprocess.run(
            ["ruff", "format", "--stdin-filename", str(OUT), "-"], input=new, capture_output=True, text=True, check=True
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        pass
    old = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    if a.check:
        if new != old:
            print("src/tarja/entities.py is stale, run: python tools/gen_entities.py")
            return 1
        print("entities.py up to date")
        return 0
    OUT.write_text(new, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(load())} entities)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
